name: Build

on:
  workflow_dispatch:

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
           name: Release-APK
           path: app/build/outputs/apk/release/
