name: Build

on:
  workflow_dispatch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        env:
          DISABLE_SVG: 1
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: LX-Netease-Music-Debug-APKs
          path: android/app/build/outputs/apk/debug/
